export const ASYNC_ACTIONS = {
  FETCH_STARTED: "FETCH_STARTED",
  FETCH_WEATHER_SUCCEEDED: "FETCH_WEATHER_SUCCEEDED",
  FETCH_FORECAST_SUCCEEDED: "FETCH_FORECAST_SUCCEEDED",
  FETCH_FAILED: "FETCH_FAILED",
  RESET_STATE: "RESET_STATE",
  TOGGLE_UNIT: "TOGGLE_UNIT",
};
